# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sign in jingdong

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16]

    steps:
    - uses: actions/checkout@v2
    - run: cd Script
    - uses: actions/checkout@v2
      with: 
        ref: master
    - run: cd ..
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        node Script/JD_DailyBonus.js
